In [2]:
import torch
import numpy as np
import torch.nn.functional as F
import torch.nn as nn
import enum
import matplotlib.pyplot as plt

#  

#  

# <font size=10>初始化</font>

In [ ]:
x = torch.empty(3, 4, dtype=torch.float)
x = torch.zeros(5, 3, dtype=torch.int8)
x = torch.ones_like(x)
x = torch.ones(3, 4)
x = torch.tensor([3, 4, 6], dtype=torch.int32, device="cpu")
x = x.new_ones(3, 4)
# print(x)
x = torch.rand(4, 4)  # U(0, 1)
x = torch.randn(4, 4)
x = torch.randn_like(x)

notes: `x = x.new_ones()`

new_ones(size, dtype=None, device=None, requires_grad=False) $\rightarrow$ Tensor

By default, the returned Tensor has the same `torch.dtype` and `torch.device` as this tensor.

In [ ]:
x_usqz_1 = torch.unsqueeze(x, dim=1)
x_usqz_0 = torch.unsqueeze(x, dim=0)
x_usqz_m1 = torch.unsqueeze(x, dim=-1)
x_usqz_m2 = torch.unsqueeze(x, dim=-2)
# 可以从shape看出不同dim的区别
print(x.shape)
print(x_usqz_1.size())
print(x_usqz_0.shape)
print(x_usqz_m1.size())
print(x_usqz_m2.size())
print(x)
print(x_usqz_1)
print(x_usqz_0)
print(x_usqz_m1)
print(x_usqz_m2)

#  

#  

# 数据类型转换

In [134]:
tensor = torch.FloatTensor(x)  # 转换成float32

#   

#  

# 简单计算

In [332]:
x = torch.ones((3, 4))
y = torch.ones_like(x)
# print(x + y)
# print(torch.add(x, y))
# print(x.add_(y))


tensor([[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])

## torch.sum()
`sumsum(input, dim, keepdim=False, dtype=None)`

**参数**

- input, dtype: 略
- dim: 求和时，求和索引所在的维度标号
- keepdim: 为``True``时，输出张量与原张量形状维度相同，否则会比原张量低至少 1 维

In [ ]:
x = torch.ones((3, 4, 5))
print(torch.sum(x, dim=0, keepdim=True).shape)
print(torch.sum(x, dim=1, keepdim=True).shape)

print(x.sum((0, 1), keepdim=True))
print(x.sum((0, 2), keepdim=True))
print(x.sum((1, 0), keepdim=True))
print(x.sum((1, 2), keepdim=True))
print(x.sum((2, 0), keepdim=True))
print(x.sum((2, 1), keepdim=True))

print(x.sum(2, keepdim=True).sum(1, keepdim=True))

#  

#  

# PyTorch & NumPy

#### 数据转换

In [ ]:
np_data = np.arange(16).reshape((4, 4))

# np to torch
torch_data = torch.from_numpy(np_data)

# torch to np
torch_2_np = torch_data.numpy()

print(
    "np_data:\n", np_data,
    "\n\ntorch_data:\n", torch_data,
    "\n\ntorch_2_np:\n", torch_2_np
)

#### 函数区别

In [ ]:
torch_data = torch_data.flatten()
print(
    "np:\n", np_data.dot(np_data),
    "\n\ntorch:\n", torch_data.dot(torch_data)  # Torch的dot只能用于一维数组
)

#   

#  

# <font size=8>常用函数</font>

### `x = y.view(*shape)`

返回一个与 y 数值相同，但形状为指定形状的 tensor x，而 x 必须与 y 的形状和 stride 兼容，Otherwise, `contiguous` needs to be called before the tensor can be
viewed

In [ ]:
x = torch.tensor(range(24)).reshape(3, 8)
print(x.view(3, 2, 4))
print(x.view(3, 2, 4, 1))
print(x.view(-1, 6))  # ‘-1’可自动推断维度
print(x.view(1, -1))  # .view(1, n) 返回拉直的二维数组
print(x.view(-1))  # 仅有 -1 时返回拉直的一维数组

- ### `contiguous(memory_format=torch.contiguous_format)`

Returns a contiguous in memory tensor containing the same data as `self` tensor. If `self` tensor is already in the specified memory format, this function returns the `self` tensor.

Args:
    memory_format (class:`torch.memory_format`): the desired memory format of returned Tensor..

In [ ]:
print(x.contiguous())

## torch.Tensor.expand()
`<tensor>.expand(*sizes)`

返回一个由`<tensor>`张成的新张量。

当`<tensor>`有一个维度为 1 时，例如 dim=1 的维度上，则可以在 dim=1 的纬度上扩展为更**大**的维度，即原 dim=1 维度值可以由 1 增大至任何整数；此外可以将`<tensor>`扩展为更**高**维的张量，但新张量的 -1, ..., -n, ( n=`len(<tensor>.shape)` )维上的维度值中非 1 的维度值应与 `<tensor>` 的维度中对应值相等

当`<tensor>`没有维度为 1 时，其只能被扩展为更**高**维的张量，其原则与上相同；

`*sizes`某一维为 -1 时，表示不改变该维的值，当把`<tensor>`扩展为更**高**维的张量时，第一个维数的值不能为 -1；

扩展一个张量不会分配新的内存，而只会在现有张量上创建一个新的视图(new view)，在这个视图中通过将`stride`设为0，来将尺寸为1的维度扩展为更大的尺寸。大小为 1 的任何维度都可以扩展为任意值，而不需要分配新的内存，故在对变量进行赋值等操作时，**注意名词绑定的问题**

In [ ]:
x = torch.tensor([17])
print(x.expand(7, 13))

In [ ]:
x = torch.tensor([[1]])
print(x.expand(7, 13))

In [ ]:
x = torch.tensor([2, 3, 4])
print(x.expand(7, 3))

In [ ]:
x = torch.tensor([2, 3, 4])
print(x.expand(2, 7, 3))

In [ ]:
x = torch.tensor([[2], [3], [4]])
print(x.expand(2, 2, 3, 7))  # 必须为 expand(n1, n1, 3, n3)

In [ ]:
x = torch.tensor([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]])
print(x.expand(2, 2, 3, 5))  # 必须为 expand(n1, n1, 3, 5)
print(x.expand(3, -1, 5))

## torch.Tensor.expand_as()
`expand_as(other)`

**说明**

返回一个和`other`形状相同的tensor，更多有关``expand``详见`torch.Tensor.expand`

In [328]:
a = torch.tensor([[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 7, 7]])
b = torch.tensor([[1, 3, 3, 1], [4, 4, 5, 6], [4, 5, 6, 9]])
c = a.eq(b)
# c = c.view(-1).float().sum(0, keepdim=True)
c = c.view(-1).float()
print(type(c))
print(c[:1])

<class 'torch.Tensor'>
tensor([1.])


#  

#  

# CUDA张量
可以利用`x.to(<device>)`来制定将张量移动至特定设备上运行

以下代码在GPU可用时的预期输出为：
```
tensor([-0.4181], device='cuda:0')
tensor([-0.4181], dtype=torch.float64)
```

In [249]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)  # or to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))  # `.to()` can also change dtype together

In [12]:
x = [[[[1, 0.23], [4, 0.24]], 0.6],
     [[[1, 0.23], [4, 0.24]], 0.8],
     [[[1, 0.23], [4, 0.24]], 0.8]]
x = np.array(x)
print(type(x[:2, 0]))

<class 'numpy.ndarray'>
