In [1]:
import torch
import numpy as np

# torch -- Overview

DESCRIPTION
The torch package contains data structures for multi-dimensional
tensors and mathematical operations over these are defined.
Additionally, it provides many utilities for efficient serializing of
Tensors and arbitrary types, and other useful utilities.

It has a CUDA counterpart, that enables you to run your tensor computations
on an NVIDIA GPU with compute capability >= 3.0.

PACKAGE CONTENTS
    \_C
    \_VF
    \_\_config__
    \_\_future__
    \_appdirs
    \_classes
    \_jit_internal
    \_linalg_utils
    \_lobpcg
    \_lowrank
    \_namedtensor_internals
    \_ops
    \_overrides
    \_six
    \_storage_docs
    \_tensor_docs
    \_tensor_str
    \_torch_docs
    \_utils
    \_utils_internal
    autograd (package)
    backends (package)
    contrib (package)
    cuda (package)
    distributed (package)
    distributions (package)
    for_onnx (package)
    functional
    futures (package)
    hub
    jit (package)
    multiprocessing (package)
    nn (package)
    onnx (package)
    optim (package)
    quantization (package)
    quasirandom
    random
    serialization
    sparse (package)
    storage
    tensor
    testing (package)
    types
    utils (package)
    version

**SUBMODULES**
- classes
- cpp
- ops

**CLASSES**
- builtins.Exception(builtins.BaseException)
    - FatalError
    - torch.jit.Error
- builtins.object
    - BoolTensor
    - ByteTensor
    - CharTensor
    - DoubleTensor
    - FloatTensor
    - IntTensor
    - LongTensor
    - ShortTensor
    - device
    - dtype
    - finfo
    - iinfo
    - layout
    - memory_format
    - qscheme
    - torch.\_C.Generator
    - torch.autograd.grad_mode.set_grad_enabled
- builtins.tuple(builtins.object)
    - Size
- pybind11_builtins.pybind11_object(builtins.object)
    - torch.\_C.AggregationType
    - torch.\_C.Argument
    - torch.\_C.ArgumentSpec
    - torch.\_C.BenchmarkConfig
    - torch.\_C.BenchmarkExecutionStats
    - torch.\_C.Block
    - torch.\_C.BufferDict
    - torch.\_C.CallStack
    - torch.\_C.Capsule
    - torch.\_C.Code
    - torch.\_C.CompilationUnit
    - torch.\_C.CompleteArgumentSpec
    - torch.\_C.ConcreteModuleType
    - torch.\_C.ConcreteModuleTypeBuilder
    - torch.\_C.DeepCopyMemoTable
    - torch.\_C.ErrorReport
    - torch.\_C.ExecutionPlan
    - torch.\_C.ExtraFilesMap
    - torch.\_C.FileCheck
    - torch.\_C.FunctionSchema
    - torch.\_C.Future
    - torch.\_C.Gradient
    - torch.\_C.Graph
    - torch.\_C.GraphExecutorState
    - torch.\_C.IODescriptor
    - torch.\_C.LiteScriptModule
    - torch.\_C.MobileOptimizerType
    - torch.\_C.ModuleDict
    - torch.\_C.Node
    - torch.\_C.ParameterDict
    - torch.\_C.PyTorchFileReader
    - torch.\_C.PyTorchFileWriter
    - torch.\_C.ScriptClass
    - torch.\_C.ScriptMethod
    - torch.\_C.ScriptObject
        - torch.\_C.ScriptModule
    - torch.\_C.ThroughputBenchmark
    - torch.\_C.TracingState
    - torch.\_C.Type
        - torch.\_C.AnyType
        - torch.\_C.BoolType
        - torch.\_C.ClassType
        - torch.\_C.DeviceObjType
        - torch.\_C.DictType
        - torch.\_C.FloatType
        - torch.\_C.FutureType
        - torch.\_C.IntType
        - torch.\_C.InterfaceType
        - torch.\_C.ListType
        - torch.\_C.NoneType
        - torch.\_C.NumberType
        - torch.\_C.OptionalType
        - torch.\_C.PyObjectType
        - torch.\_C.RRefType
        - torch.\_C.StringType
        - torch.\_C.TensorType
        - torch.\_C.TupleType
    - torch.\_C.Use
    - torch.\_C.Value
    - torch.jit.ScriptFunction
- torch.\_C.BoolStorageBase(builtins.object)
    - BoolStorage(torch.\_C.BoolStorageBase, torch.storage.\_StorageBase)
- torch.\_C.ByteStorageBase(builtins.object)
    - ByteStorage(torch.\_C.ByteStorageBase, torch.storage.\_StorageBase)
- torch.\_C.CharStorageBase(builtins.object)
    - CharStorage(torch.\_C.CharStorageBase, torch.storage.\_StorageBase)
- torch.\_C.DoubleStorageBase(builtins.object)
    - DoubleStorage(torch.\_C.DoubleStorageBase, torch.storage.\_StorageBase)
- torch.\_C.FloatStorageBase(builtins.object)
    - FloatStorage(torch.\_C.FloatStorageBase, torch.storage.\_StorageBase)
- torch.\_C.IntStorageBase(builtins.object)
    - IntStorage(torch.\_C.IntStorageBase, torch.storage.\_StorageBase)
- torch.\_C.LoggerBase(pybind11_builtins.pybind11_object)
    - torch.\_C.LockingLogger
    - torch.\_C.NoopLogger
- torch.\_C.LongStorageBase(builtins.object)
    - LongStorage(torch.\_C.LongStorageBase, torch.storage.\_StorageBase)
- torch.\_C.ShortStorageBase(builtins.object)
    - ShortStorage(torch.\_C.ShortStorageBase, torch.storage.\_StorageBase)
- torch.\_C.\_TensorBase(builtins.object)
    - Tensor
- torch.autograd.grad_mode.\_DecoratorContextManager(builtins.object)
    - torch.autograd.grad_mode.enable_grad
    - torch.autograd.grad_mode.no_grad
- torch.storage.\_StorageBase(builtins.object)
    - BoolStorage(torch.\_C.BoolStorageBase, torch.storage.\_StorageBase)
    - ByteStorage(torch.\_C.ByteStorageBase, torch.storage.\_StorageBase)
    - CharStorage(torch.\_C.CharStorageBase, torch.storage.\_StorageBase)
    - DoubleStorage(torch.\_C.DoubleStorageBase, torch.storage.\_StorageBase)
    - FloatStorage(torch.\_C.FloatStorageBase, torch.storage.\_StorageBase)
    - IntStorage(torch.\_C.IntStorageBase, torch.storage.\_StorageBase)
    - LongStorage(torch.\_C.LongStorageBase, torch.storage.\_StorageBase)
    - ShortStorage(torch.\_C.ShortStorageBase, torch.storage.\_StorageBase)

#  

# torch.bmm()
`bmm(input, mat2, deterministic=False, out=None) -> Tensor`

**Doctring**

对 batch 层级的`input`和`mat2`张量做矩阵乘法，这要求`input`和`mat2`有相同的 batch 数；如果`input`是 $(b \times n \times m)$ 的张量，`mat2`是 $(b \times m \times p)$ 的张量，则`out`是 $(b \times n \times p)$ 的张量。此函数不支持`broadcast <broadcasting-semantics>`

**Args**

- input, mat2, out: 略

- deterministic: 使用更快的非确定性计算或较慢的确定性计算，该参数只适用于 sparse-dense CUDA bmm

**Type**:      builtin_function_or_method

#  

#  

# torch.cuda.set_device()
`torch.cuda.set_device(device: Union[torch.device, str, int]) -> None`

**Docstring**

设定目前使用的设备；Usage of this function is discouraged in favor of `device`，大多情况下最好使用``CUDA_VISIBLE_DEVICES``环境变量

**Args**

- device: 可以是`torch.device`对象或整数，即设定的运行设备，若参数为负数，则此函数为无操作 (no-op) 函数

**File**:   \torch\cuda\\\_\_init__.py

**Type**:      function

#  

#  

# torch.device()

`torch.device`返回一个代表着运行设备的对象，`torch.Tensor`会被分配至该设备上运行；其接受的参数包括一个设备类型（`'cpu'`或`'cuda'`）及设备类型相应的设备序号，若没有指定设备序号，即使调用了`torch.cuda.set_device()`，此函数仍会返回当前的设备作为设备类型，例如通过设备`"cuda"`构造的张量等价于通过`'cuda:X'`构造的张量，其中 X 为`torch.cuda.current_device()`的返回值；

一个`torch.Tensor`的设备可以通过`Tensor.device`属性获得，其设备可以通过一个字符串或字符串+设备序号来构造；

In [5]:
print(torch.device('cuda:0'))
print(torch.device("cuda", 1))

cuda:0
cuda:1


#  

#  

# torch.load()
```python
torch.load(
    f,
    map_location=None,
    pickle_module=<module 'pickle' from '...\\lib\\pickle.py'>,
    **pickle_load_args,
)
```

``torch.load``从一个文件中加载由`torch.save`函数保存的对象，其使用 Python 的 unpickle 工具，但专门处理存储；这些存储首先在 CPU 上被反序列化，然后被移动到保存它们的设备，如果该过程失败则就会引发异常，然而可以利用``map_location``动态地将存储重新映射到另一组设备。

若`map_location`为可调用函数，则对每个带有`storage`和`location`两个参数的序列化存储，该函数都会被调用一次，其中`storage`为存储在 CPU 上初始反序列化的结果；每个序列化存储都有一个与之关联的位置标签，其标识着保存存储的设备，这个标签是传递给`map_location`的第二个参数；对于 CPU 张量，内置的位置标签为``'cpu'``，GPU 张量的内置位置标签则是``'cuda:device_id'``。`map_location`应返回一个存储或是``None``，若其返回一个存储，则该存储将被视为已经移动到正确设备上的最终反序列化后的对象，返回``None``时`torch.load`将执行默认指令。

若`map_location`是`torch.device`类对象或代表设备标签的字符串，此时其用于表示所有张量被加载到的位置；若`map_location`是一个字典，则其用于将所文件中位置标记（键）重新映射到指定着存储位置的位置标记（值）

User extension 可以通过`torch.serialization.register_package`来注册他们自己的位置标签、标记及反序列化的方法；

当使用`torch.load()`从含有 GPU 张量的文件加载张量时，这些张量会默认加载至 GPU；若想避免 GPU 内存内存占用增加，可以通过调用`torch.load(... , map_location='cpu')`函数，再调用`load_state_dict`函数加载模型检查点。默认情况下为避免在 Python 3 中加载由 Python 2 保存的文件时可能抛出的异常``UnicodeDecodeError: 'ascii' codec can't decode byte 0x...``，函数使用``utf-8``模式解码；若该默认解码方式不适用，可通过传递关键字参数来指明对象的加载方式；例如`encoding='latin1'`通过``latin1``编码将内容解码为字符串，`encoding='bytes'`将其转换为字节数组，随后可以通过``byte_array.decode(...)``来对字节数组进行解码；

**Args**

- f: 可以是一个类文件的对象，其必须含有`read`、`readline`、`tell`、`seek`方法的实现，或是一个包含文件名的字符串

- map_location: 其可以是指明了怎样重新映射存储位置的一个函数、`torch.device`类、字符串、字典

- pickle_module: 用于 unpickle 元数据及对象的模块，其必须与用于序列化文件的`pickle_module`属性相匹配

- pickle_load_args: 传递给`pickle_module.load`和`pickle_module.Unpickler`的关键参数，例如`errors=...`

**警告！**`torch.load()`隐式的使用``pickle``模块，这个过程可能是不安全的，期间可能会产生恶意数据，其可能在 unpickle 期间执行任意未知代码，故不要加载不信任的来源或可能被篡改的数据


**Type**： function

### Example:

In [ ]:
torch.load('tensors.pt')
torch.load('tensors.pt', map_location=torch.device('cpu'))  # Load all tensors onto the CPU
torch.load('tensors.pt', map_location=lambda storage, loc: storage)  # Load all tensors onto the CPU, using a function
torch.load('tensors.pt', map_location=lambda storage, loc: storage.cuda(1))  # Load all tensors onto GPU 1
torch.load('tensors.pt', map_location={'cuda:1':'cuda:0'})  # Map tensors from GPU 1 to GPU 0
with open('tensor.pt', 'rb') as f:
    buffer = io.BytesIO(f.read())
    torch.load(buffer)  # Load tensor from io.BytesIO object
torch.load('module.pt', encoding='ascii')# Load a module with 'ascii' encoding for unpickling

#  

#  

# torch.no_grad()
`torch.no_grad()`

**Docstring**

返回一个禁用梯度计算的上下文管理器，当不会调用`Tensor.backward()`时，禁用梯度计算对模型推断帮助，其可以减少计算的内存消耗；该模式下，即使输入张量指明了`requires_grad=True`，计算时也会是`requires_grad=False`。在使用`torch.enable_grad`上下文管理器时，此模式不起作用。该上下文管理器是 local thread 的，其不影响其他线程的计算

Also functions as a decorator. (Make sure to instantiate with parenthesis.)

**File**:  \torch\autograd\grad_mode.py

**Type**:           type 

**Example**

In [ ]:
x = torch.tensor([1.], requires_grad=True)
with torch.no_grad():
    y = x * 2
    print(y.requires_grad)

In [6]:
@torch.no_grad()
def doubler(x):
    return x * 2

y = doubler(x)
print(y.requires_grad)

False


#  

# torch.norm()
`torch.norm(input, p='fro', dim=None, keepdim=False, out=None, dtype=None)`
**Docstring**:

根据给定的张量返回矩阵范数或向量范数，该函数可能会被弃用，请使用`torch.linalg.norm`

**Args**:
- input, out, dtype: pass
- p: 可以是整型、浮点型、`inf`、`-inf`、`'fro'`、`'nuc'`等，指范数的阶；默认`'fro'`；核范数只能作用于 2 维矩阵
oder| 矩阵范数 | 向量范数
:---| :-------| :-------
`None`|Frobenius 范数| 2 范数
`'fro'`|Frobenius 范数|--
`'nuc'`|核范数$tr\left(\sqrt{X^TX}\right)$|--
其他|`dim=None`时与向量范数相同|`sum(abs(x)**ord)**(1./ord)`
- dim: 若为整型，则沿指定维度计算向量范数；若为 2 元元祖或 2 元列表，则沿指定维度计算矩阵范数；若为 None，当输入为 2 维张量时计算矩阵范数，当输入为 1 维张量时计算向量范数，当输入为高于 2 维的张量时沿最后一维计算向量范数
- keepdim: 返回张量是否保持`dim`所指维度，默认 False；当`dim=None`且`out=None`时此参数无效

**File**:     \torch\functional.py

**Type**:      function

### Example

In [ ]:
>>> d = torch.arange(8, dtype= torch.float).reshape(2,2,2)
>>> torch.norm(d, dim=(1,2))
tensor([ 3.7417, 11.2250])
>>> torch.norm(d[0, :, :]), torch.norm(d[1, :, :])
(tensor(3.7417), tensor(11.2250))

In [4]:
x = torch.arange(1, 7, dtype= torch.float).reshape(1, 2, 3, 1).expand(2, 2, 3, 4)
print(torch.norm(x))
print(torch.norm(x, p=1))
print(torch.norm(x, p=2))
print(torch.norm(x, p='fro'))
print(torch.norm(x, p=float('inf')))
print(torch.norm(x, p='nuc', dim=[0, 1]))
print(torch.norm(x, p='fro', dim=-1))
print(torch.norm(x, p='fro', dim=[-1, -2]))

tensor(26.9815)
tensor(168.)
tensor(26.9815)
tensor(26.9815)
tensor(6.)
tensor([[5.8310, 5.8310, 5.8310, 5.8310],
        [7.6158, 7.6158, 7.6158, 7.6158],
        [9.4868, 9.4868, 9.4868, 9.4868]])
tensor([[[ 2.,  4.,  6.],
         [ 8., 10., 12.]],

        [[ 2.,  4.,  6.],
         [ 8., 10., 12.]]])
tensor([[ 7.4833, 17.5499],
        [ 7.4833, 17.5499]])


#  

# torch.sort()

`sort(input, dim=-1, descending=False, out=None) -> (Tensor, LongTensor)`

**Docstring**

将`input`张量元素值沿给定`dim`升序/降序排列，并返回元组`(values, indices)`，其中
`indices`为对应`values`在原张量中的索引

**Args**

- input, dim, out: 略

- descending: 决定进行升序/降序排列

**Type**

builtin_function_or_method

In [ ]:
x = torch.arange(1, 25).reshape(1, 2, 3, 4)
values, ids = torch.sort(x, descending=True, dim=-2)
print("values", values, "indices", ids, sep="\n")

In [ ]:
x = torch.arange(1, 13).reshape(3, 4)
ids = torch.sort(x, descending=True, dim=-1)[1]
print(ids)

#  

# torch.sum()
`torch.sum(input, dim, keepdim=False, *, dtype=None) -> Tensor`

Returns the sum of each row of the `input` tensor in the given dimension `dim`. If `dim` is a list of dimensions, reduce over all of them.

**Args**

- input: 略
- dim: 可以是整数或整数列表，要进行加和的维度，即如果`dim`是一列表，则对所有指明的维度进行加和
- keepdim: 输出张量维度的数量是否与输入相同
- dtype: 默认为 None，指明时输入张量会先被转换成目标数据类型在进行函数操作

**Type**:      builtin_function_or_method

### Example

In [17]:
x = torch.arange(1, 7).reshape(2, 3, 1).expand(2, 3, 4)
y = torch.sum(x, dim=[-1, -2])
y = torch.sum(x).item()
print(y)

84


#  

# torch.topk()
`torch.topk(input, k, dim=None, largest=True, sorted=True, out=None)
 <tensor>.topk(k, dim=None, largest=True, sorted=True, out=None)`

**Docstring**

对于给定的张量，返回两个张量，第一个为给定维度上 k 个最大/小值，第二个为最大/小值对应在原张量`input`中`dim`维上的索引

**Args**

- input, k: 略

- dim: 排序的维度，默认 -1；如$(a \times b \times c)$的 tensor，dim=0时返回两个 $(k \times b \times c)$ tensor

- largest: 决定了返回最大值或最小值，`True`时返回 k 个最大值，`False`时返回 k 个最小值

- sorted: 决定是否以排序的顺序返回各元素

- out (tuple): the output tuple of (Tensor, LongTensor) that can be optionally given to be used as output buffers

In [10]:
a = torch.tensor(range(24)).reshape(2, 3, 4)
x = a.topk(k=1, dim=1, largest=True, sorted=True)

print(torch.topk(a, 1, dim=0)[0].shape)
print(torch.topk(a, 1, dim=1)[0].shape)
print(torch.topk(a, 1, dim=2)[0].shape)

torch.Size([1, 3, 4])
torch.Size([2, 1, 4])
torch.Size([2, 3, 1])


In [23]:
output = torch.tensor(range(24)).reshape(4, 6)
_, pred = output.topk(k=1, dim=1, largest=True, sorted=True)
pred = pred.t()
target = torch.tensor([5, 32, 17, 11])
correct = pred.eq(target.view(1, -1).expand_as(pred))

correct[:10].view(-1).float().sum(0)

tensor(1.)

In [27]:
def softmax(X):
    out = np.exp(X)
    return out / np.sum(out)

X = np.random.uniform(0.2, 0.42, [10])
print(X)

[0.20232375 0.40433996 0.36665815 0.37907609 0.35556185 0.34073845
 0.39835009 0.26194353 0.2003465  0.38420623]


In [28]:
print(softmax(X))

[0.08783213 0.10749491 0.10351968 0.1048132  0.10237734 0.10087096
 0.10685296 0.09322791 0.08765863 0.10535228]


#  

# torch.unsqueeze()
`unsqueeze(input, dim) -> Tensor`

**Args**:
- input: the input tensor.
- dim (int): 要插入维数的索引值，取值范围在``[-input.dim() - 1, input.dim() + 1)``之间

**Type**:      builtin_function_or_method

### Example
```python
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, dim=0).shape)  # => torch.Size([1, 4])
print(torch.unsqueeze(x, dim=1).shape)  # => torch.Size([4, 1])
```

#  

# Torch.Tensor
## torch.Tensor.all()
`<tensor>.all() -> bool`

Returns True if all elements in the tensor are True, False otherwise.

Example::

    >>> a = torch.rand(1, 2).bool()
    >>> a
    tensor([[False, True]], dtype=torch.bool)
    >>> a.all()
    tensor(False, dtype=torch.bool)

.. function:: all(dim, keepdim=False, out=None) -> Tensor

Returns True if all elements in each row of the tensor in the given
dimension :attr:`dim` are True, False otherwise.

If :attr:`keepdim` is ``True``, the output tensor is of the same size as
:attr:`input` except in the dimension :attr:`dim` where it is of size 1.
Otherwise, :attr:`dim` is squeezed (see :func:`torch.squeeze`), resulting
in the output tensor having 1 fewer dimension than :attr:`input`.

Args:
    dim (int): the dimension to reduce
    keepdim (bool): whether the output tensor has :attr:`dim` retained or not
    out (Tensor, optional): the output tensor

Example::

    >>> a = torch.rand(4, 2).bool()
    >>> a
    tensor([[True, True],
            [True, False],
            [True, True],
            [True, True]], dtype=torch.bool)
    >>> a.all(dim=1)
    tensor([ True, False,  True,  True], dtype=torch.bool)
    >>> a.all(dim=0)
    tensor([ True, False], dtype=torch.bool)
Type:      method_descriptor

In [ ]:
x = torch.tensor([[True, False], [False, True]])
y = torch.tensor([[False, False], [True, True]])
print((x * y).float().mean())

## torch.Tensor.item()
`<tensor_name>.item()`

**Docstring**

以标准 Python 值的形式返回该张量的值，其只适用于只有一个元素的张量；其他情况见`torch.Tensor.tolist`，这个操作是不可导的；

**Type**:      method_descriptor
### Example
```python
x = torch.tensor([1])
x.item()  # ==> 1
```

## torch.Tensor.transpose()
`<tensor_name>.transpose(dim0, dim1)`、`torch.transpose(input, dim0, dim1)`

**Docstring**

将张量在维度`dim0`和`dim1`上进行转置，输出张量和输入张量共享底层存储空间，即改变一个张量的内容也会改变另一个张量的内容

**Type**:      method_descriptor

In [ ]:
x = torch.arange(1, 25).reshape(1, 2, 3, 4)
print(x.transpose(1, 2))
print(x.transpose(1, 3))
print(x.transpose(0, 1))
print(x.transpose(0, 2))
print(x.transpose(0, 3))

In [ ]:
torch.Tensor.grad_fn

#  

# torch.cat()
`torch.cat(tensors, dim=0, out=None) -> Tensor`

**Docstring**:

将一个张量序列`tensors`在给定维度上进行拼接，其中`tensors`可以是元祖或列表；进行拼接的各张量的形状除进行拼接的维度之外，其余维度应当相同，或为空张量；`torch.cat`可以看作`torch.split`和`torch.chunk`的逆运算；

**Type**:      builtin_function_or_method

### Example

In [22]:
z = torch.tensor([])
x = torch.arange(1, 13).reshape(3, 4)
y = torch.arange(15, 19).unsqueeze(0)
print(torch.cat([x, z], 0))
y = torch.cat([x, y], 0, out=z)
print(z, y, sep="\n")

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [15., 16., 17., 18.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [15., 16., 17., 18.]])


In [7]:
y = torch.cat([x, x, x], 0)
y = torch.cat((x, x, x), 1)
y = torch.cat((x, x, x), 2)