In [2]:
import tensorflow as tf

In [1]:
import numpy as np

# tf.add()
***
`tf.add(x, y, name=None)`

__Docstring__

`math.add`支持broadcasting，而`AddN`不支持；更多有关 broadcasting
[here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

`tf.subtract()`, `tf.divide()`类似

__Args__

- x: `bfloat16`, `half`, `float32`, `float64`, `uint8`, `int8`, `int16`, `int32`, `int64`, `complex64`, `complex128`, `string`类型的`Tensor`

- y: 与`x`形状相同的`Tensor`.

- name: operation's

__Type__: function

In [ ]:
tf.multiply()
tf.square()
tf.pow()
tf.sqrt()
tf.matmul()

#  

#  

# tf.constant

`tf.constant(value, dtype=None, shape=None, name='Const')`

__Docstring__

Creates a constant tensor from a tensor-like object.

Note: All eager `tf.Tensor` values are immutable (in contrast to
`tf.Variable`). There is nothing especially _constant_ about the value
returned from `tf.constant`. This function it is not fundamentally different
from `tf.convert_to_tensor`. The name `tf.constant` comes from the symbolic
APIs (like `tf.data` or keras functional models) where the `value` is embeded
in a `Const` node in the `tf.Graph`. `tf.constant` is useful for asserting
that the value can be embedded that way.

**Args**

- value: 由任意数据类型构成的标量或张量

- dtype: `None`时，输出数据类型由`value`数据类型推断得出；否则将`value`转换为指明的数据类型

- shape: `value`为一标量时，则输出为指明`shape`的元素由`value`构成的张量，`value`为张量时，输出`shape`应为*可由原张量 reshape 得到的形状*

- name: 张量名称



Raises:
  TypeError: if shape is incorrectly specified or unsupported.
  ValueError: if called on a symbolic tensor.



**Type**: function

In [66]:
x = tf.constant(True, shape=[2, 3])
x = tf.constant([True, False], dtype = tf.float32)
x = tf.constant([1., 2., 3., 4., 5., 6.], shape=[2, 3])

由于`tf.constant`将值嵌入到了`tf.Graph`，对于符号型张量会抛出异常

>>> i = tf.keras.layers.Input(shape=[None, None])
>>> t = tf.constant(i)
Traceback (most recent call last):
...
NotImplementedError: ...

`tf.constant` will _always_ create CPU (host) tensors. In order to create
tensors on other devices, use `tf.identity`. (If the `value` is an eager
Tensor, however, the tensor will be returned unmodified as mentioned above.)

Related Ops:

* `tf.convert_to_tensor` is similar but:
  * It has no `shape` argument.
  * Symbolic tensors are allowed to pass through.

    >>> i = tf.keras.layers.Input(shape=[None, None])
    >>> t = tf.convert_to_tensor(i)

* `tf.fill`: differs in a few ways:
  *   `tf.constant` supports arbitrary constants, not just uniform scalar
      Tensors like `tf.fill`.
  *   `tf.fill` creates an Op in the graph that is expanded at runtime, so it
      can efficiently represent large tensors.
  *   Since `tf.fill` does not embed the value, it can produce dynamically
      sized outputs.

#  

#  

# tf.ones()
***
`tf.ones(shape, dtype=tf.float32, name=None)`

__Args__

- shape: 当为一标量时，返回一维张量

- dtype: 略

- name: operation的

__Type__: function

In [4]:
x = 3 * tf.ones(1, dtype=tf.int8, name="test")
x = 5 + tf.zeros([3, 4], dtype=tf.float16, name=None)
print(x)

tf.Tensor(
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]], shape=(3, 4), dtype=float16)


#  

#  

# tf.fill()

`tf.fill(dims, value, name=None)`

__Docstring__

与将取值以`Const`节点嵌入计算图的`tf.constant(value, shape=dims)`不同，`tf.fill`在图运行环境中进行衡量，并支持基于其他运行环境的`tf.Tensors`的动态形状(`tf.fill` evaluates at graph runtime and supports dynamic shapes based on
other runtime `tf.Tensors`)

__Args__

- dims: 取标量时仍返回张量

- value: 略

- name: `tf.Tensor`的


__Type__: function

In [ ]:
x = 4 * tf.fill(1, value=1.2, name=None)  # ≈ np.fill()

#  

#  

# tf.cast()

`tf.cast(x, dtype, name=None)`

__Docstring__

对于`Tensor`，将`x`数据类型转换为`dtype`，对于`SparseTensor`或`IndexedSlices`，将`x.values`数据类型转换为`dtype`。

`x`与`dtype`支持的数据类型有`uint8`、`uint16`、`uint32`、`uint64`、`int8`、`int16`、`int32`、`int64`、`float16`、`float32`、`float64`、`complex64`、`complex128`、`bfloat16`。当将虚数转为实数时，只返回实部；当将实数转换为虚数时，虚部为0

``name``为运算名称

__Type__

function

In [67]:
x = tf.fill([3, 4], 2.99)
y = tf.cast(x, tf.int8)
print(y)

tf.Tensor(
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]], shape=(3, 4), dtype=int8)


#  

#  

# tf.argmax()

`tf.argmax(input, axis=None, output_type=tf.int64, name=None)`

__Docstring__

返回张量各坐标轴上最大值的索引。在数值绑定的情况下，返回值不能保证

__Args__

- input: 略

- axis: 同大多函数的`axis`设定

- output_type: 只能为`tf.int32`、`tf.int64`

- name: 操作的

__Type__

function

In [16]:
x = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8], [14, 45, 23, 5, 27]])
print(tf.argmax(x, axis=0))
print(tf.argmax(x, axis=1))
x = tf.constant([2, 2, 2])
print(tf.argmax(x))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


#  

#  

# tf.GradientTape()
Init signature: tf.GradientTape(persistent=False, watch_accessed_variables=True)
Docstring:     
Record operations for automatic differentiation.

Operations are recorded if they are executed within this context manager and
at least one of their inputs is being "watched".

Trainable variables (created by `tf.Variable` or `tf.compat.v1.get_variable`,
where `trainable=True` is default in both cases) are automatically watched.
Tensors can be manually watched by invoking the `watch` method on this context
manager.

For example, consider the function `y = x * x`. The gradient at `x = 3.0` can
be computed as:

```python
x = tf.constant(3.0)
with tf.GradientTape() as g:
  g.watch(x)
  y = x * x
dy_dx = g.gradient(y, x) # Will compute to 6.0
```

GradientTapes can be nested to compute higher-order derivatives. For example,

```python
x = tf.constant(3.0)
with tf.GradientTape() as g:
  g.watch(x)
  with tf.GradientTape() as gg:
    gg.watch(x)
    y = x * x
  dy_dx = gg.gradient(y, x)     # Will compute to 6.0
d2y_dx2 = g.gradient(dy_dx, x)  # Will compute to 2.0
```

By default, the resources held by a GradientTape are released as soon as
GradientTape.gradient() method is called. To compute multiple gradients over
the same computation, create a persistent gradient tape. This allows multiple
calls to the gradient() method as resources are released when the tape object
is garbage collected. For example:

```python
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as g:
  g.watch(x)
  y = x * x
  z = y * y
dz_dx = g.gradient(z, x)  # 108.0 (4*x^3 at x = 3)
dy_dx = g.gradient(y, x)  # 6.0
del g  # Drop the reference to the tape
```

By default GradientTape will automatically watch any trainable variables that
are accessed inside the context. If you want fine grained control over which
variables are watched you can disable automatic tracking by passing
`watch_accessed_variables=False` to the tape constructor:

```python
with tf.GradientTape(watch_accessed_variables=False) as tape:
  tape.watch(variable_a)
  y = variable_a ** 2  # Gradients will be available for `variable_a`.
  z = variable_b ** 3  # No gradients will be available since `variable_b` is
                       # not being watched.
```

Note that when using models you should ensure that your variables exist when
using `watch_accessed_variables=False`. Otherwise it's quite easy to make your
first iteration not have any gradients:

```python
a = tf.keras.layers.Dense(32)
b = tf.keras.layers.Dense(32)

with tf.GradientTape(watch_accessed_variables=False) as tape:
  tape.watch(a.variables)  # Since `a.build` has not been called at this point
                           # `a.variables` will return an empty list and the
                           # tape will not be watching anything.
  result = b(a(inputs))
  tape.gradient(result, a.variables)  # The result of this computation will be
                                      # a list of `None`s since a's variables
                                      # are not being watched.
```

Note that only tensors with real or complex dtypes are differentiable.
Init docstring:
Creates a new GradientTape.

Args:
  persistent: Boolean controlling whether a persistent gradient tape
    is created. False by default, which means at most one call can
    be made to the gradient() method on this object.
  watch_accessed_variables: Boolean controlling whether the tape will
    automatically `watch` any (trainable) variables accessed while the tape
    is active. Defaults to True meaning gradients can be requested from any
    result computed in the tape derived from reading a trainable `Variable`.
    If False users must explicitly `watch` any `Variable`s they want to
    request gradients from.
File:           d:\programmefiles\python\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\backprop.py
Type:           type
Subclasses:     LossScaleGradientTape

#  

#  

# tf.convert_to_tensor()

`tf.convert_to_tensor(value, dtype=None, dtype_hint=None, name=None)`

__Docstring__

Converts the given `value` to a `Tensor`.

该函数将各种类型的 Python 对象转化为`Tensor`类型的对象，其支持`Tensor`对象、Numpy数组、Python 列表、Python 标量。当`float`和`string`类型的 Python 列表或标量中出现`None`时，与 Numpy 将`None`转换为数值的行为不同，该函数会抛出异常

**Args**

- value: 满足其类型有已注册的`Tensor`的转换函数的对象(An object whose type has a registered `Tensor` conversion function)

- dtype: 略

- dtype_hint: 用于`dtype`为`None`时；在某些情况下，调用者在转换为张量时可能没有想到dtype，所以dtype_hint可以用作一个软首选项；若目标转换类型无法转换，则该参数等同于无效

- name: 张量名称

**Type**

function

In [ ]:
x = np.arange(12)
y = tf.convert_to_tensor(x)
print(x)
print(y)

#  

#  

# tf.reduce_min()

`tf.reduce_min(input_tensor, axis=None, keepdims=False, name=None)`

__Docstring__

等价于`np.min()`

Reduces `input_tensor` along the dimensions given in `axis`.
Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
entry in `axis`. If `keepdims` is true, the reduced dimensions
are retained with length 1.

If `axis` is None, all dimensions are reduced, and a
tensor with a single element is returned.

__Args__

- input_tensor: 应为实数类型张量

- axis, keepdims: 略

- name: operation的

__Type__

function

In [ ]:
x = tf.constant([[1, 3, 4, 0, 3], [2, 5, 1, 8, 2]])
y = tf.reduce_min(x, axis=0)  # == np.min()
y = tf.reduce_max(x, axis=1)  # == np.max()
y = tf.reduce_sum(x, axis=0)  # == np.sum()
y = tf.reduce_mean(x, axis=0)  # == np.mean()
print(y)
y = tf.reduce_prod(x, axis=0)  # == np.prod()

#  

#  

# tf.reduce_any

`tf.reduce_any(input_tensor, axis=None, keepdims=False, name=None)`

__Docstring__

沿张量某一维度执行`or`计算



For example:

```python
x = tf.constant([[True,  True], [False, False]])
tf.reduce_any(x)  # True
tf.reduce_any(x, 0)  # [True, True]
tf.reduce_any(x, 1)  # [True, False]
```

__Args__

- input_tensor: 布尔型张量

- axis, keepdims, name: 略

__Type__

function

In [ ]:
x = tf.constant(
    [[ True, False, True, False, False, True],
     [False, True, True, False, False, True]])
y = tf.reduce_any(x, axis=0)  # == np.any()
print(y)
y = tf.reduce_all(x, axis=0)  # == np.all()
print(y)

#  

#  

# tf.reduce_logsumexp()

`tf.reduce_logsumexp(input_tensor, axis=None, keepdims=False, name=None)`

__Docstring__

计算

$$\ln \left( \sum\exp(input[shape[i]])\right)$$

该函数比直接计算$\ln\left(\sum\exp(input)\right)$要稳定，其避免了指数函数和对数函数的溢出问题. 

__Args__: 略

__Type__: function

In [ ]:
x = tf.constant([[0., 0., 0.], [0., 0., 0.]])
y = tf.reduce_logsumexp(x)  # log(6)
y = tf.reduce_logsumexp(x, 0)  # [log(2), log(2), log(2)]
y = tf.reduce_logsumexp(x, 1)  # [log(3), log(3)]
y = tf.reduce_logsumexp(x, 1, keepdims=True)  # [[log(3)], [log(3)]]
y = tf.reduce_logsumexp(x, [0, 1])  # log(6)

#  

#  

# tf.one_hot()

```python
tf.one_hot(
    indices,
    depth,
    on_value=None,
    off_value=None,
    axis=None,
    dtype=None,
    name=None,
)
```
__Docstring__

Returns a one-hot tensor.

`indices`中由索引表示的位置取值为`on_value`，而其他所有位置取值为`off_value`，若期望输出为非数字类型变量，则`on_value`和`off_value`必须指明。

- `indices`为标量时，输出为长度为`depth`的向量；

- 若`indices`为长度为`features`的向量，则输出形状

    - 在axis = -1时为 $features \times depth$

    - 在axis = 0时为 $depth \times features$

- 若`indices`是形状为`[batch, features]`的矩阵，则输出形状
    
    - 在`axis == -1`时为 $batch \times features \times depth$

    - 在`axis == 1`时为 $batch \times depth \times features$

    - 在`axis == 0`时为 $batch \times batch \times features$

- 若`indices`为不规则张量，`axis`必须为正且需指代一个规则的维度，结果等价于将`one_hot`应用在不规则张量的取值上，并生成一个新的不规则张量

__Args__

- indices: 内容代表索引的`Tensor`；若`indices`的秩为 N，则输出数组的秩为 N+1，新的维度会添加在`axis`指明位置中；

- depth: 定义 one hot 维度的标量

- on_value: 输出结果中，当`indices[j] = i`时的取值，默认为 1，需与`off_value`和`dtype`数据类型匹配

- off_value: 输出结果中，当`indices[j] != i`时的取值，默认为 0，需与`on_value`和`dtype`数据类型匹配

- axis: 在shape中添加索引的位置，默认 -1

- dtype: 默认为`tf.float32`，需与`on_value`和`off_value`匹配

- name: operation's

__Type__: function

In [ ]:
x = tf.one_hot(indices=3, depth=7, on_value=6, off_value=-2, dtype=tf.int8)
print(x)

In [ ]:
'''
    axis=0时返回(6,4)数组，对于indices的元素“2”来说，其之前的索引为(1)
    则将索引“2”添加到新索引(x,y)的索引为0的位置，即x的位置，进而得到新索引(2,1)
'''
classes = 6
targets = [1, 2, 4, 3]
x = tf.one_hot(indices=targets, depth=classes, axis=0)
print(x)
'''
    axis=0时返回(6,4)数组，对于indices的元素“2”来说，其之前的索引为(1)
    则将索引“2”添加到新索引(x,y)的索引为1的位置，即y的位置，进而得到新索引(1,2)
''' 
y = tf.one_hot(indices=[5, 2, 4, 3], depth=6, axis=1)

In [ ]:
'''
    axis=0时返回(5,2,3)数组，对于indices的元素“4”来说，其之前的索引为(0,2)
    则将索引“4”添加到新索引(x,y,z)的索引为0的位置，即x的位置，进而得到新索引(4,0,2)
''' 
x = tf.one_hot(indices=[[0, 2, 4], [1, 0, 3]], depth=5, axis=0)
y = tf.one_hot(indices=[[0, 2, 4], [1, 0, 3]], depth=5, axis=1)
z = tf.one_hot(indices=[[0, 2, 4], [1, 0, 3]], depth=5, axis=2)
print(x, y, z, sep="\n\n")

In [100]:
indices = tf.ragged.constant([[0, 1], [2]])  # (2, 1)
x = tf.one_hot(indices=indices, depth=3)  # output: (2, None, 3)
print(x)

<tf.RaggedTensor [[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]], [[0.0, 0.0, 1.0]]]>


#  

#  

In [ ]:
tf.where()

#  

#  

In [105]:
tf.bool

<dtype: 'bool'>


#  

#  

#  

#  

#  

#  

#  

#  

#  

#  

#  

#  

#  