In [1]:
import numpy as np

<center>

# 数组堆叠

## np.tile()

`np.tile(A, reps)`

#### Doctrings
根据`reps`对`A`进行重复、堆叠并构造出一个新数组，其中
- A : 类数组型，即被重复的数组；
- reps : 类数组型，其第 i 个元素代表在`A`在第 i 个坐标轴上重复的次数。记`reps`长度为 d，返回数组的维度为`max(d, A.ndim)`：
    - 若`A.ndim < d`，则`A`会通过添加新的坐标轴来扩充至 d 维；例如形状为 (3,) 的数组会被扩充为 (1, 3) 的 2D 数组，或形状为 (1, 1, 3) 的 3D 数组。如果需要扩充的维度并非上面提到的这种，例如希望扩充后形状为 (3, 1) ，应在调用此函数之前提前将`A`扩种至 d 维（例2）
    - 若``A.ndim > d``，则`reps`会通过在其前面添加 1 来扩充至`A.ndim`的维数，例如`A`形状为 (2, 3, 4, 5)，则形状为 (2, 2) 的`reps`会被视为 (1, 1, 2, 2)（例1）

官方建议，尽管此函数可以用于广播，但强烈建议使用`numpy`内置的广播操作和函数。

#### See Also
- repeat : Repeat elements of an array.
- broadcast_to : Broadcast an array to a new shape


#### Examples
1. 在 axis=0 的维度上重复 2 次，`A.ndim > d`：

In [19]:
A = np.array(
    [[0, 1, 2],
     [3, 4, 5]]
)
B = np.tile(A, reps=2)
print(B)

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


2. `2=A.ndim < d=3` 时，`A`会先扩充为`[1, 2, 3]`的形状，再进行堆叠；例如在 axis=0 的维度上重复 3 次、axis=1 的维度上重复 2 次、在 axis=2 的维度上重复 1 次，：

In [28]:
print(np.tile(A, (3, 2, 1)))

[[[0 1 2]
  [3 4 5]
  [0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]
  [0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]
  [0 1 2]
  [3 4 5]]]


3. 如果想让`A`第一个维度大小保持不变，仅在第二个维度重复，需要利用`np.newaxis`：

In [19]:
A_ = A[:, np.newaxis, :]

print(np.tile(A_, reps=[1, 3, 1]))

[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[3 4 5]
  [3 4 5]
  [3 4 5]]]


## 

## np.repeat()
`np.repeat(a, repeats, axis=None)`

#### Docstring

根据`repeats`对`a`中的元素，返回数组的形状除了在`axis`轴之外，其余与`a`相同。其中
- `a`应为类数组类型；
- `repeats`应为整型或整型数组，即每个元素重复的次数；当其为整型数组时，`axis`不能为`None`，`repeats`的第 i 个元素代表`a`在`axis`轴上第 i 个切片重复的次数（例3、4）
- `axis`应为整型，用于指定在哪个维度上对元素进行重复操作；默认将输入数组拉直再对元素进行重复（例1）



#### See Also

- tile : Tile an array.
- unique : Find the unique elements of an array.


#### Examples

1. `repeats`为整型且不指定`axis`时，默认先拉直再重复：

In [6]:
a = np.array(
    [[1, 2, 3],
     [3, 4, 5]]
)
print(np.repeat(a, 2))

[1 1 2 2 3 3 3 3 4 4 5 5]


2. `repeats`为整型，对数组在指定坐标轴上进行重复：

In [7]:
print(np.repeat(a, 2, axis=0))
print(np.repeat(a, 2, axis=1))

[[1 2 3]
 [1 2 3]
 [3 4 5]
 [3 4 5]]
[[1 1 2 2 3 3]
 [3 3 4 4 5 5]]


3. `repeats`为整型数组，对 a 第一行元素重复 4 次、第二行元素重复 2 次

In [8]:
np.repeat(a, [4, 2], axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [3, 4, 5],
       [3, 4, 5]])

4. `repeats`为整型数组，对 a 第一列元素重复 4 次、第二列元素重复 2 次、第三列元素重复 3 次

In [9]:
np.repeat(a, [4, 2, 3], axis=1)

array([[1, 1, 1, 1, 2, 2, 3, 3, 3],
       [3, 3, 3, 3, 4, 4, 5, 5, 5]])

5. `np.repeat`与`np.tile`的区别：前者是逐元素/逐切片重复的，而后者是整个复制的。从可视化角度来看，前者对每个像素点的范围进行放大，后者对整个图片进行堆叠

In [56]:
a = np.array([[1, 2, 3], [3, 4, 5]])
print(np.repeat(a, 2, axis=1))
print(np.tile(a, 2))

print(np.repeat(a, 2, axis=0))
print(np.tile(a, [2, 1]))

[[1 1 2 2 3 3]
 [3 3 4 4 5 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
[[1 2 3]
 [1 2 3]
 [3 4 5]
 [3 4 5]]
[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


## 

# 

# 

<center>

# 变维、转置 etc.

## `np.broadcast(self, /, *args, **kwargs)`

对输入的参数`in1`、`in2`使用传播机制进行组合，并返回一个封装了结果的对象，该对象具有`shape`和`nd`属性，并可以用作迭代器；其中

#### See Also
- broadcast_arrays
- broadcast_to
- broadcast_shapes

#### Examples
1. 广播后返回的对象：

In [40]:
# Manually adding two vectors, using broadcasting:

x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
for i in b:
    print(i)

(1, 4)
(1, 5)
(1, 6)
(2, 4)
(2, 5)
(2, 6)
(3, 4)
(3, 5)
(3, 6)


手动广播机制与内置广播机制对比：

In [41]:
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
print(out)
print(x + y)

[[2.12199579e-314 9.88131292e-324 4.24399158e-314]
 [2.12199579e-314 6.36598737e-314 1.06099790e-313]
 [8.48798317e-314 6.36598738e-314 1.06099790e-313]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


## np.broadcast_to()
`np.broadcast_to(array, shape, subok=False)`

对数组进行广播，以得到指定形状的数组；返回数组是只读的，且其多个元素可能会指向同一个内存位置；

##### Args
- array : 类数组类型；
- shape : 元祖类型；新的形状必须与原数组形状在广播机制下兼容，否则会抛出异常；
- subok : 布尔型；如果为 True，则会传递子类；否则默认返回基类类型的数组；

##### See Also
- broadcast
- broadcast_arrays
- broadcast_shapes

##### Examples

In [13]:
x = [[ 0,  1,  2,  3],
     [ 4,  5,  6,  7],
     [ 8,  9, 10, 11]]
print(np.broadcast_to(x, (2, 3, 4)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


## 

## np.expand_dims()
`np.expand_dims(a, axis)`

在`axis`位置插入一个新坐标轴，并返回原数组的一个视图 (即 in-place 操作的)；这里`axis`可以是整型或整型元祖；

    .. deprecated:: 1.13.0
        Passing an axis where ``axis > a.ndim`` will be treated as ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will be treated as ``axis == 0``. This behavior is deprecated.

    .. versionchanged:: 1.18.0
        A tuple of axes is now supported.  Out of range axes as described above are now forbidden and raise an `AxisError`.

Returns
-------
result : ndarray
    View of `a` with the number of dimensions increased.

##### See Also
- squeeze : The inverse operation, removing singleton dimensions
- reshape : Insert, remove, and combine dimensions, and resize existing ones
- doc.indexing, atleast_1d, atleast_2d, atleast_3d

##### Examples
1. 该函数是 inplace 的

In [15]:
x = np.array([1, 2])
y = np.expand_dims(x, axis=0)
y[0, 0] = 3
print(x == y[0])

[ True  True]


In [ ]:
``axis`` may also be a tuple:

>>> y = np.expand_dims(x, axis=(0, 1))
>>> y
array([[[1, 2]]])

>>> y = np.expand_dims(x, axis=(2, 0))
>>> y
array([[[1],
        [2]]])

Note that some examples may use ``None`` instead of ``np.newaxis``.  These
are the same objects:

>>> np.newaxis is None
True
File:      d:\programfiles\miniconda3\lib\site-packages\numpy\lib\shape_base.py
Type:      function

## 

## np.reshape()

`np.reshape(a, newshape, order='C')`
`ndarray.reshape(shape, order='C')`

##### Args
- a : 类数组型
- newshape : 整型或整型元祖，应与原数组的形状兼容；当该参数为单个整数时，原数组会被拉直；当该参数中含有 -1 时，相应维度上的维数会根据原数组形状自行推断得到
- order : 可以是`'C'`、`'F'`、`'A'`；以 C 顺序还是 Fortran 顺序读取原数组以及写入新数组，其中 C 顺序对数组最后一个维度的操作最快，而对第一个操作最慢，F 相反；注意`C`和`F`不会改变底层数组的内存布局，改变索引顺序；`A`则表示，如果`a`在内存中是 Fortran 连续的，则以类似 Fortran 的索引顺序读取，否则按照 C 顺序；


##### Examples
1. `reshape`常用情景：

In [22]:
a = np.array([[1,2,3], [4,5,6]])
print(np.reshape(a, (3,-1)))

[[1 2]
 [3 4]
 [5 6]]


2. `reshape`可以看作先根据给定的索引顺序分解数组，再使用与分解相同的索引顺序将元素插入到新数组中，这可以通过设定读取和写入的顺序看出来：

In [24]:
a = -np.arange(0, 6).reshape((3, 2))
a_F = a.reshape((2, 3), order="F")
print(a_F)

# is equivalent to
a_ravel = np.ravel(a, order="F")
a_reshape = np.reshape(a_ravel, (2, 3), order="F")
print(a_ravel)
print(a_reshape)

[[ 0 -4 -3]
 [-2 -1 -5]]
[ 0 -2 -4 -1 -3 -5]
[[ 0 -4 -3]
 [-2 -1 -5]]


3. 在不对数据进行复制的情况下改变数组形状并非总是可行的；如果希望在复制数据时引发错误，需要应将新形状赋值给数组的`shape`属性

In [25]:
a = np.zeros(20)
a.shape = (10, 2)  #
print(a)
# A transpose makes the array non-contiguous
b = a.T
# Taking a view makes it possible to modify the shape without modifying the initial object.
c = b.view()
# c.shape  # will raise an error

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


# 

# 

## np.dstack()
`np.dstack(tup)`
将一个由数组构成的序列沿第三个坐标轴进行拼接。其等价于先将 2D 数组
Stack arrays in sequence depth wise (along third axis).

This is equivalent to concatenation along the third axis after 2-D arrays of shape `(M,N)` have been reshaped to `(M,N,1)` and 1-D arrays of shape `(N,)` have been reshaped to `(1,N,1)`. Rebuilds arrays divided by `dsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters

tup : sequence of arrays
    The arrays must have the same shape along all but the third axis.
    1-D or 2-D arrays must have the same shape.

Returns

stacked : ndarray
    The array formed by stacking the given arrays, will be at least 3-D.

##### See Also
- concatenate : Join a sequence of arrays along an existing axis.
- stack : Join a sequence of arrays along a new axis.
- block : Assemble an nd-array from nested lists of blocks.
- vstack : Stack arrays in sequence vertically (row wise).
- hstack : Stack arrays in sequence horizontally (column wise).
- column_stack : Stack 1-D arrays as columns into a 2-D array.
- dsplit : Split array along third axis.

##### Examples

In [2]:
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.dstack((a,b))


>>> a = np.array([[1],[2],[3]])
>>> b = np.array([[2],[3],[4]])
>>> np.dstack((a,b))


array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

## np.stack()
`np.stack(arrays, axis=0, out=None)`

将一个由类数组组成的序列`arrays`沿新的坐标轴`axis`拼接起来，其中`arrays`的每个类数组应具有相同的形状

##### See Also
- concatenate : Join a sequence of arrays along an existing axis.
- block : Assemble an nd-array from nested lists of blocks.
- split : Split array into a list of multiple sub-arrays of equal size.

##### Examples

In [14]:
arrays = [np.arange(6).reshape((2, 3))+i for i in range(2)]
print(np.stack(arrays, axis=0))
print(np.stack(arrays, axis=1))
print(np.stack(arrays, axis=2))

[[[0 1 2]
  [3 4 5]]

 [[1 2 3]
  [4 5 6]]]
[[[0 1 2]
  [1 2 3]]

 [[3 4 5]
  [4 5 6]]]
[[[0 1]
  [1 2]
  [2 3]]

 [[3 4]
  [4 5]
  [5 6]]]


In [ ]:
>>> np.stack(arrays, axis=2).shape
(3, 4, 10)

>>> a = np.array([1, 2, 3])
>>> b = np.array([4, 5, 6])
>>> np.stack((a, b))
array([[1, 2, 3],
       [4, 5, 6]])

>>> np.stack((a, b), axis=-1)
array([[1, 4],
       [2, 5],
       [3, 6]])
File:      d:\programfiles\miniconda3\lib\site-packages\numpy\core\shape_base.py
Type:      function

In [23]:
a = np.arange(2*4*6).reshape((2, 4, 6))
print(a)
print(a.mean(axis=(-1, -2)))
print(a)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]]]
[11.5 35.5]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]]]


In [25]:
54/2/6

4.5