In [1]:
import numpy as np

<h2>
    <pre>
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=np._NoValue,
    *,
    where=np._NoValue,
)
    </pre>
</h2>



对整个数组`a`或沿指定`axis`计算数组切片的算术平均值，其中

- a : 应是类数组类型；
- axis : 应是`None`、整型、或整型组成的元祖：
    - 默认`None`时对整个数组计算
    - 当`axis`为整型数时，操作会**在指定的坐标轴上**进行；例如对于一个 3 维数组，`axis=1`的数学表达式如下，示例参见例 1：
        $$out[x_0, z_0] = N_y^{-1} \sum_{y} a[x_0, y, z_0]$$
    - 当`axis`为整型元祖时，操作会**在所有指定的坐标轴上**进行；例如对于一个 3 维数组，`axis=(1, 2)`，的数学表达式如下，示例参见例 2：
        $$out[x_0] = N_y^{-1}N_z^{-1} \sum_{y, z} a[x_0, y, z]$$
- dtype : 输出数组的数据类型，若输入数组为整型，则输出为 float64；对于浮点型数组，输出数组的数据类型与输入相同；但需要说明的是，精度低的输入类型可能会导致结果不准确，特别是`float32`（例3）；默认情况下，指定`float16`输出结果时会使用`float32`作为中间值来提高精度；
- out : 若为`None`，则返回一个新的数组；否则返回指向输出数组的一个引用，此时该数组的形状必须与预期计算结果相同，数据类型可以不同
- keepdims : 布尔型，如果设为 True，则输出数组的`axis`轴仍会保留为长度 1；如果传递的默认值`np._NoValue`，则`keepdims`不会传递给`ndarray`子类的`mean`方法，如果该子类方法没有实现`keepdims`，这将有可能会引发异常；
- where : 布尔型组成的类数组，指定哪些元素在计算均值时会被包括在内，详情参见`numpy.ufunc.reduce`



#### See Also

- average : Weighted average
- std, var, nanmean, nanstd, nanvar


#### Examples
1. `axis`取整型数时，在相应的轴上计算结果，公式见上

In [2]:
a = np.array(
    [[[1, 2, 3], [4, 5, 6]],
    
    [[-1, -2, -3], [-4, -5, -6]]]
)
assert np.mean(a, axis=0)[1, 2] == np.mean(a[:, 1, 2])
print(np.mean(a, axis=0))

assert np.mean(a, axis=1)[1, 2] == np.mean(a[1, :, 2])
print(np.mean(a, axis=1))

assert np.mean(a, axis=2)[1, 0] == np.mean(a[1, 0, :])
print(np.mean(a, axis=2))

[[0. 0. 0.]
 [0. 0. 0.]]
[[ 2.5  3.5  4.5]
 [-2.5 -3.5 -4.5]]
[[ 2.  5.]
 [-2. -5.]]


2. 当`axis`为整型元祖时，计算均值时会在元祖指定的轴上都计算均值：

In [3]:
assert np.mean(a, axis=(2, 1))[1] == np.mean(a[1, :, :])
print(np.mean(a, axis=(2, 1)))

[ 3.5 -3.5]


3. 对于在单精度浮点数，`mean`函数计算结果可能会不准确

In [ ]:
a = np.ones((2, 512*512), dtype=np.float32)
a[1, :] = 0.1
print(np.mean(a))
print(np.mean(a, dtype=np.float64))

4. 利用`where`参数来指定计算均值时所包括的元素，例如将第 0、2 行考虑在内，以及将第 0、3 列考虑在内：

In [ ]:
a = np.array([[5, 1, 3, 5],
              [4, 2, 8, 2],
              [1, 3, 9, 6]])
print(np.mean(a, where=[[True], [False], [True]]))
assert np.mean(a, where=[[True], [False], [True]]) == np.mean(a[[0, 2], :])

print(np.mean(a, where=[True, False, False, True]))
assert np.mean(a, where=[True, False, False, True]) == np.mean(a[:, [0, 3]])

# 

## `np.dot(a, b, out=None)`



对`a`和`b`执行两个数组的点积，这里`a`和`b`应是类数组类型；具体来说：

- 若`a`和`b`都是 1D 数组，则执行向量内积，但这里对于复向量**不**取共轭
- 若`a`和`b`都是 2D 数组，则通过函数`matmul`或`a @ b`执行矩阵乘法
- 若`a`或`b`其中一个是标量，则执行标量积
- 若`a`都是 k-D 数组，`b`是 1D 数组，则对`a`和`b`的最后一个维度进行诸元素的相乘核求和，即





$${dot(a, b)}[n_1, \cdots, n_{k-1}] = \sum_{i} a[n_1, \cdots, n_{k-1}, i] \cdot b[i]$$
- 若`a`都是 k-D 数组，`b`是 m-D 数组，其中 M≥2，则对`a`的最后一个维度和`b`的倒数第二个维度进行诸元素的相乘核求和，即

$$dot(a, b)[n_1, \cdots, n_{k-1}, n_1', \cdots, n_{l-2}', n_l'] = \sum_i (a[n_1, \cdots, n_{k-1}, i] \cdot b[n_1', \cdots, n_{l-2}', i, n_l'])$$


这里`out`指输出数组，若默认为`None`，则返回一个新的数组；否则返回指向输出数组的一个引用，此时该数组的形状、数据类型必须与预期计算结果相同，而且应当是 C-连续的

##### See Also

- vdot : Complex-conjugating dot product.
- tensordot : Sum products over arbitrary axes.
- einsum : Einstein summation convention.
- matmul : '@' operator as method with out parameter.
- linalg.multi_dot : Chained dot product.

##### Examples

In [5]:
a = [[1, -1], [3, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[ 2, -1],
       [14,  5]])

In [7]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print(np.dot(a, b)[2,3,2,1,2,2])
print(sum(a[2,3,2,:] * b[1,2,:,2]))

499128
499128


# 