In [1]:
import numpy as np
import sys

<div align=center>

# 矩阵生成
</div>

# np.empty()
`np.empty(shape, dtype=float, order='C')`

**Docstring**

返回不具有初始化项的具有给定形状和类型的数组，与`zeros`等不同，没有对元素进行初始化，进而可能会稍微快一些

**Args**

- shape: int or tuple of int

- dtype: 默认`numpy.float64`.

- order: `'C'`或`'F'`，以行为主的存储方式（C 语言方式）还是列为主（Fortran 语言方式）的存储方式存储数组


**See Also**

- empty_like : Return an empty array with shape and type of input.

**Type**

builtin_function_or_method

**Examples**

In [ ]:
x = np.empty([3, 4])
print(x)
x = np.empty([3, 4], dtype=int)
print(x)

#  

# np.copy

`np.copy(a, order='K')`

**Docstring**

等价于`np.array(a, copy=True)`，副本与原对象不绑定在同一数值上

**参数**

- order: {'C', 'F', 'A', 'K'}，决定了输出结果的内存布局
    - 'C': C-order,
    - 'F': F-order, 
    - 'A': 如果`a`是Fortran连续的，则为'F'，否则为'C' 
    - 'K': 尽可能的与`a`内存布局相同

**Type**

function

In [4]:
x = np.array(range(24)).reshape(4, 6)
y = np.copy(x)
y[0, 0] = 3
print(x)
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 3  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [27]:
x = np.zeros(3)
x[1] = 1; x[2] = 2
if x.tolist() == [1, 2, 3]:
    print(x)

#  

# np.ndarray.copy()

`a.copy(order='C')`


**参数**

- order: {'C', 'F', 'A', 'K'}，决定了输出结果的内存布局
    - 'C': C-order,
    - 'F': F-order, 
    - 'A': 如果`a`是Fortran连续的，则为'F'，否则为'C' 
    - 'K': 尽可能的与`a`内存布局相同

**Type**

method_descriptor

#  

# np.copyto()


`copyto(dst, src, casting='same_kind', where=True)`

**Docstring**

将值从一个数组复制到另一个数组，必要时进行 broadcasting

Raises a TypeError if the `casting` rule is violated, and if
`where` is provided, it selects which elements to copy.



Parameters
----------
dst : ndarray
    The array into which values are copied.
src : array_like
    The array from which values are copied.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur when copying.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64 to float32, are allowed.
      * 'unsafe' means any data conversions may be done.
where : array_like of bool, optional
    A boolean array which is broadcasted to match the dimensions
    of `dst`, and selects elements to copy from `src` to `dst`
    wherever it contains the value True.
Type:      function

In [10]:
x = 4 * np.random.randn(12)
print(x)
y = np.array(range(9))
x[1:-2] = y
print(x)

[-0.55726102  3.35587423 -2.64781587 -1.14678239  1.93481062  3.42564306
 -0.92006697 -3.75494862  5.62975266  2.91954578  2.92717907 -2.66854019]
[-0.55726102  0.          1.          2.          3.          4.
  5.          6.          7.          8.          2.92717907 -2.66854019]


#  

# np.where()

`np.where(condition, [x, y])`

**Docstring**

根据所提供的条件，满足时返回`x`，不满足时返回`y`；当只提供`condition`时，该函数等价于``np.asarray(condition).nonzero()``，即满足条件的索引数组，索引数组的数量原数组的维数相同；

**Args**
- condition: 布尔型数组，当`condition=True`时返回`x`，否则返回`y`
- x, y: 任意类型数组，`x`, `y`和`condition`在形状上应为兼容的

**Type**: function

In [6]:
x = np.array([[1, 2, 3, 4], [3, 2, 1, 2], [3, 4, 3, 2]])
y = np.where(x == 3)
print(y)
x = np.where(
    [[True, False], [True, True]],
    [[1, 2], [3, 4]],
    [[9, 8], [7, 6]]
)
print(x)
x, y = np.ogrid[:3, :4]
z = np.where(x < y, x, 10 + y)
print(z)

(array([0, 1, 2, 2], dtype=int64), array([2, 0, 0, 2], dtype=int64))
[[1 8]
 [3 4]]
[[10  0  0  0]
 [10 11  1  1]
 [10 11 12  2]]


#  

# np.int_()
`np.int_(self, /, *args, **kwargs)`

**Docstring**:

带符号的整型，与 Python 的`int`和 C 的``long``, Numpy``np.int32``兼容

**Character code**: ``'l'``

**Canonical name**: ``np.int_``

**File**:   \numpy\\\_\_init__.py

**Type**:           type

#  

# np.load()

``` python
np.load(
    file,
    mmap_mode=None,
    allow_pickle=False,
    fix_imports=True,
    encoding='ASCII',
)
```
**Docstring**

从``.npy``、``.npz``或 pickle 文件中加载数组或 pickled 对象，对于``.npz``文件，返回的 `NpzFile` 类的实例化对象需避免泄漏文件描述符，加载的包括了目标数组的文件通常包括``pickle``模块，这样操作对于错误的或恶意构造的数据是不安全的，应考虑设置``allow_pickle=False``

__Args__

- file: 要加载的文件，可以是类文件的对象、字符串或pathlib.Path；类文件对象需要支持``seek()``和``read()``方法， methods，对于 Pickled 文件而言，类文件对象还需要支持``readline()``方法

    - 如果文件包含pickle数据，那么将返回存储在pickle中的任何对象
    - 如果文件是``.npy``文件，则返回单一数组
    - 如果文件是``.npz``文件，则返回一个字典型对象，其由 ``{filename: array}`` 键值对组成，存档中的每个文件都有一个，且返回值以类似于`open`的方式支持上下文管理器协议：
    ```
    with load('foo.npz') as data:
        a = data['a']
    ```

- mmap_mode: 可以为`None`、`r+`、`r`、`w+`、`c`，若不为时`None`，则使用给定模式对文件进行内存映射(memory map)，对映射模式的详细说明参见`numpy.memmap`；一个内存映射得到的数组保存在片上，然而该数组可以像 `ndarray` 被访问及被切片；当不需要将整个文件读入内存，而只需访问大文件的小片段是，内存映射能够提供很多便利

- allow_pickle: 是否允许加载保存在 npy 文件的 pickle 对象，默认为`False`；禁止 pickle 的原因包括安全性，因为加载 pickle 数据过程可能会执行任意代码，若允许 pickle，加载对象常常会失败

- fix_imports: 只当在 Python 3 中加载由 Python 2 生成的 pickle文件时使用，其中包括包含目标数组的npy/npz文件

- encoding : 指明读取 Python 2 字符串时使用什么编码，只当在 Python 3 中加载由 Python 2 生成的 pickle文件时使用，其中包括包含目标数组的npy/npz文件，仅支持"latin1"、"ASCII"、“bytes”，其他取值可能破坏数字数据，默认为"ASCII"




**Type**:      function

In [ ]:
np.save('./load_test/load_test1', np.array([[1, 2, 3], [4, 5, 6]]))
data = np.load('./load_test/load_test1.npy')
print(data)

In [ ]:
# Store compressed data to disk, and load it again
a=np.array([[1, 2, 3], [4, 5, 6]])
b=np.array([1, 2])
np.savez('./load_test/load_test2', a=a, b=b)
data = np.load('./load_test/load_test2.npz')
print(data["a"])
print(data["b"])
data.close()

In [ ]:
# Mem-map the stored array, and then access the second row directly from disk:
X = np.load('./load_test/load_test1.npy', mmap_mode='r')
X[1, :]

#  

# np.asarray()

`np.asarray(a, dtype=None, order=None)`

**Args**

- a: 可以是列表、由元组组成的列表、元组、元组组成的元组、列表组成的元组、ndarray，若`a`为 ndarray 的子类，将返回 ndarray 的基类

- dtype: 略

- order: `C`或`F`，即使用行主内存(C语言风格)表示还是列主内存表示(Fortran语言格式)，默认为C


**See Also**

- asanyarray: Similar function which passes through subclasses.

- ascontiguousarray: Convert input to a contiguous array.

- asfarray: Convert input to a floating point ndarray.

- asfortranarray : Convert input to an ndarray with column-major memory order.

- asarray_chkfinite : Similar function which checks input for NaNs and Infs.

- fromiter : Create an array from an iterator.

- fromfunction : Construct an array by executing a function on grid positions.

**Type**

function

In [44]:
x = np.array([[1, 2], [3, 4]])
y = np.asarray(x, order="F")
z = np.asarray(x, order="C")
print(y, z, sep="\n\n", end="\n\n")
print(y is x, z is x, sep="\n", end="\n\n")

[[1 2]
 [3 4]]

[[1 2]
 [3 4]]

False
False



In [ ]:
# ragged list
x = [[1, 2], [3, 4], [2]]
x = np.asarray(x)
y = np.array(x)
print(x)
print(y)
print(x == y)
print(x is y)

In [ ]:
# 与`asanyarray`相反，ndarray的子类没有被传递（啥意思？）
print(issubclass(np.recarray, np.ndarray))
a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
print(np.asarray(a) is a)
print(np.asanyarray(a) is a)

#  

# np.savez_compressed

`np.savez_compressed(file, *args, **kwds)`

**Docstring**

将若干数组以``.npz``的压缩文件格式保存起来。``.npz``格式文件是根据其保存的变量命名的压缩文件，该文件是经过``zipfile.ZIP_DEFLATED``压缩，且其包含文件均为``.npy``格式文件，``.npy``格式文件的描述详见`numpy.lib.format`

当通过`load`打开一个已保存的``.npz``文件时，将返回一个`NpzFile`类字典的对象，该对象支持查阅它的数组列表(利用``.files``属性)及数组本身

**Args**

- file: 可以是保存数据的字符串型的文件名、已打开的文件或类文件对象；若为字符串或路径，且该文件不存在，则自动将为期添加扩展名``.npz``

- args: 保存到文件里的数组；由于 Python 无法知道`savez`外数组的名字，故数组默认保存为"arr_0"，"arr_1"等；该参数可以是任意表达式；

- kwds: 若给定值，数组将以给定值作为名称保存在文件里，否则默认为"arr_0"，"arr_1"等



**See Also**

- numpy.save : Save a single array to a binary file in NumPy format.

- numpy.savetxt : Save an array to a file as plain text.

- numpy.savez : Save several arrays into an uncompressed ``.npz`` file format

- numpy.load : Load the files created by savez_compressed.

**Type**

function

In [ ]:
x = np.random.rand(3, 2)
y = np.random.rand(4)
np.savez_compressed('./test_files/savez_compressed_test/test1', x=x, y=y)
loaded = np.load('./test_files/savez_compressed_test/test1.npz')
print(np.array_equal(x, loaded['x']))
print(np.array_equal(y, loaded['y']))

# 

# np.argmax()
`np.argmax(a, axis=None, out=None)`

返回最大值所在的索引，若含有多个相同的最大值，则返回最先出现的那个值的索引，即较小的索引

**Args**
- a: 输入数组或类数组
- axis: 默认情况下，该函数会将数组`a`拉直，再进行排序，并返回值最大的元素对应的索引，此时返回结果为单个整数；当指明`axis`时，则等价于排序时以该坐标轴上的索引为变量进行比较，例如`axis=1`时，排序的过程为$\displaystyle\max_{idx1} \mathtt{a[idx0, idx1, idx2]}$，此时返回结果的形状等价于为原数组形状去掉`axis`上的元素得到的形状；
- out : 如果指定了数组，结果则会直接 insert 至该数组；该数组的形状应与返回的结果相匹配；


**File**:   \numpy\core\fromnumeric.py

**Type**:      function

**Examples**

In [36]:
a = np.array([[[5, 0, 3, 3], [7, 9, 3, 5], [2, 4, 7, 9]],
              [[8, 8, 1, 6], [7, 7, 8, 1], [5, 9, 8, 9]]])
assert np.argmax(a) == 5  # the idx of the 1st max value "9" is 5
assert a[np.unravel_index(5, a.shape)] == 9
np.argmax(a, axis=0)
# => [[1, 1, 0, 1], [0, 0, 1, 0], [1, 1, 1, 0]]
np.argmax(a, axis=1)  # => [[1, 1, 2, 2], [0, 2, 1, 2]]
np.argmax(a, axis=2)  # => [[0, 1, 3], [0, 2, 1]]

array([[1, 1, 0, 1],
       [0, 0, 1, 0],
       [1, 1, 1, 0]], dtype=int64)

In [37]:
x = np.array([[4,2,3], [1,0,3]])
a = np.argmax(x, axis=-1)  # => [0 2]
np.take_along_axis(x, np.expand_dims(a, axis=-1), axis=-1)
# np.take_along_axis(x, np.expand_dims(a, axis=-1), axis=-1).squeeze(axis=-1)

array([[4],
       [3]])

#  

#  

# np.add()
```python
add(x1, x2, /,
    out=None,
    *,
    where=True,
    casting='same_kind',
    order='K',
    dtype=None,
    subok=True[, signature, extobj]
)
```

**Args**

- x1, x2: 若``x1.shape != x2.shape``，他们必须对同一个形状是 broadcastable 的，同时该形状作为输出数组的形状

- out: 可以是ndarray、None、或这两者组成的元组；传值必须与输入 broadcast 得到的形状相同；没有传值则返回新分配的数组；元组(可能仅作为关键字参数)的长度必须与输出的数量相等

- where: 可以是类数组array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
- 其他参数参见`ufunc docs <ufuncs.kwargs>`.

**Type**

ufunc


Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])
Class docstring:
Functions that operate element by element on whole arrays.

To see the documentation for a specific ufunc, use `info`.  For
example, ``np.info(np.sin)``.  Because ufuncs are written in C
(for speed) and linked into Python with NumPy's ufunc facility,
Python's help() function finds this page whenever help() is called
on a ufunc.

A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.

Calling ufuncs:


op(*x[, out], where=True, **kwargs)
Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.

The broadcasting rules are:

* Dimensions of length 1 may be prepended to either array.
* Arrays may be repeated along dimensions of length 1.

Parameters
----------
*x : array_like
    Input arrays.
out : ndarray, None, or tuple of ndarray and None, optional
    Alternate array object(s) in which to put the result; if provided, it
    must have a shape that the inputs broadcast to. A tuple of arrays
    (possible only as a keyword argument) must have length equal to the
    number of outputs; use None for uninitialized outputs to be
    allocated by the ufunc.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
**kwargs
    For other keyword-only arguments, see the :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
r : ndarray or tuple of ndarray
    `r` will have the shape that the arrays in `x` broadcast to; if `out` is
    provided, it will be returned. If not, `r` will be allocated and
    may contain uninitialized values. If the function has more than one
    output, then the result will be a tuple of arrays.

#  

# np.argsort()
`np.argsort(a, axis=-1, kind=None, order=None)`

**Docstring**

Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified
by the `kind` keyword. It returns an array of indices of the same shape as
`a` that index data along the given axis in sorted order.

**Args**
- a : 略
- axis : 默认 -1，None 时对所有元素进行操作
- kind: 可以是`'quicksort'`, `'mergesort'`, `'heapsort'`, `'stable'`，即排序所使用的算法，默认`'quicksort'`，其中`'stable'`和`'mergesort'`都在幕后 (under the covers) 使用 timsort，且实际的实现方式会随着数据类型的不同而不同；`'mergesort'`仅用于与旧版本的兼容性（retained for backwards compatibility）不同的排序算法见`np.sort`
- order : 字符串或字符串构成的列表，当' a '是一个定义了字段的数组时，这个参数指定了首先比较哪个字段，第二个字段，等等。可以将单个字段指定为字符串，但不需要指定所有字段，但仍将使用未指定的字段(按照它们在dtype中出现的顺序)来中断绑定。   When `a` is an array with fields defined, this argument specifies which fields to compare first, second, etc.  A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.


**File**:     \numpy\core\fromnumeric.py

**Type**:      function

### Examples

In [5]:
x = np.array([[0, 3, -1], [2, 2, 7]])
idx = np.argsort(x, axis=1)  # [[2, 0, 1], [0, 1, 2]]
x_sorted = np.take_along_axis(x, idx, axis=1)
print(x_sorted)

[[2 0 1]
 [0 1 2]]
[[-1  0  3]
 [ 2  2  7]]


In [7]:
idx = np.unravel_index(np.argsort(x, axis=None), x.shape)

# Sorting with keys:
x = np.array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])
print(np.argsort(x, order=('x','y')))
print(np.argsort(x, order=('y','x')))

[1 0]
[0 1]


#  

#  

# np.unique()
```python
np.unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
)
```
**Docstring**

返回`unique`和`unique_x`。对于`unique`数组，若原数组没有重复元素，则输出原数组；否则对于重复出现的元素，只输出第一个出现的元素。对于`unique_x`数组，`return_index`、`return_inverse`、`return_counts`的不同设定还将返回不同数组，详情见下


**Args**

- ar: 若非指明`axis`，否则输出总为一维数组

- return_index: 为真则除返回`unique`之外，还返回`unique_indices`，其元素为`unique`中元素在`ar`中第一次出现时的索引；指明`axis`时，为`axis`上的索引

- return_inverse: 为真则除返回`unique`之外，还返回`unique_inverse`，其元素为`ar`中每一个元素在`unique`中的索引；指明`axis`时，为`axis`上的索引

- return_counts: 为真则除返回`unique`之外，还返回`unique_counts`，其元素为`unique`每个元素出现在`ar`的次数

- axis: 如果是None，`ar`将被拉直。如果是整数，指定轴的维度上的数组将被视为一维数组并被拉直，更多细节参见注释。`axis`不支持包含对象的对象数组或结构化数组（structured arrays）



**See Also**

numpy.lib.arraysetops : Module with a number of other functions for performing set operations on arrays.

Notes
-----
When an axis is specified, the subarrays indexed by the axis are sorted.
This is done by making the specified axis the first dimension of the array
(move the axis to the first dimension to keep the order of the other axes)
and then flattening the subarrays in C order. The flattened subarrays are
then viewed as a structured type with each element given a label, with the
effect that we end up with a 1-D array of structured types that can be
treated in the same way as any other 1-D array. The result is that the
flattened subarrays are sorted in lexicographic order starting with the
first element.

**Type**

function

### Examples
一维数组：

In [2]:
x = np.array(['a', 'b', 'b', 'c', 'a'])
u, idx = np.unique(x, return_index=True)
for i in range(len(u)):
    print("the first index of `{}` in `x` is {}".format(u[i], idx[i]))
print(x[idx] == u)
u, inv = np.unique(x, return_inverse=True)
print(u, inv)
for i in range(len(x)):
    print("the {}-th value in `x`, which is {}, has the index {} in `u` ".format(i+1, x[i], inv[i]))
# Reconstruct the input array `x` from the unique values:
print(u[inv])

the first index of `a` in `x` is 0
the first index of `b` in `x` is 1
the first index of `c` in `x` is 3
[ True  True  True]
['a' 'b' 'c'] [0 1 1 2 0]
the 1-th value in `x`, which is a, has the index 0 in `u` 
the 2-th value in `x`, which is b, has the index 1 in `u` 
the 3-th value in `x`, which is b, has the index 1 in `u` 
the 4-th value in `x`, which is c, has the index 2 in `u` 
the 5-th value in `x`, which is a, has the index 0 in `u` 
['a' 'b' 'b' 'c' 'a']


In [ ]:
x = list("bcdghvdcxnbshcvdsbbjhvdbvvcghsdvchds")
print(np.unique(x))

多维数组在不指明`axis`时直接返回排序后的一维数组：

In [3]:
x = np.random.randint(0, 4, [4, 6])
print(x)

[[1 3 1 3 2 2]
 [3 0 3 2 3 1]
 [3 3 0 3 0 0]
 [2 3 2 0 3 1]]


In [4]:
print(np.unique(x, return_index=True))
print(np.unique(x, return_inverse=True))
print(np.unique(x, return_counts=True))

(array([0, 1, 2, 3]), array([7, 0, 4, 1], dtype=int64))
(array([0, 1, 2, 3]), array([1, 3, 1, 3, 2, 2, 3, 0, 3, 2, 3, 1, 3, 3, 0, 3, 0, 0, 2, 3, 2, 0,
       3, 1], dtype=int64))
(array([0, 1, 2, 3]), array([ 5,  4,  5, 10], dtype=int64))


指明`axis`时的返回值

In [ ]:
x = np.random.randint(low=0, high=2, size=[9, 3])
print(x)

In [ ]:
u, idx = np.unique(x, axis=0, return_index=True)
print(u, idx)
u, inv = np.unique(x, axis=0, return_inverse=True)
print(u, inv)
u, cnt = np.unique(x, axis=0, return_counts=True)
print(u, cnt)

#  

#  

# np.nonzero()
`np.nonzero(a)` or `arr.nonzero()`

**Docstring**

返回一个元组，元组包含了若干 ndarray，ndarray的数量为输入数组`a`的维度数，其中第 n 个数组的元素代表原数组第 n 个纬度上非零元素的索引；`a`中的元素总是以行为主、C 语言风格的顺序进行检测和返回。

若希望返回的非零元素的索引以元素为单位而不是以维度为单位排列的话，须使用`argwhere`。

当输入为 0 维数组或标量时，该函数等效于``nonzero(atleast1d(a))``

While the nonzero values can be obtained with ``a[nonzero(a)]``, it is recommended to use ``x[x.astype(bool)]`` or ``x[x != 0]`` instead, which will correctly handle 0-d arrays.

**See Also**

- flatnonzero: Return indices that are non-zero in the flattened version of the input array.

- count_nonzero: Counts the number of non-zero elements in the input array.

**Examples**

In [ ]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(np.nonzero(x))
y = np.transpose(np.nonzero(x))  # equivalent to np.argwhere(x)
print(y)
y = x[np.nonzero(x)]
print(y)

In [ ]:
A common use for ``nonzero`` is to find the indices of an array, where
a condition is True.  Given an array `a`, the condition `a` > 3 is a
boolean array and since False is interpreted as 0, np.nonzero(a > 3)
yields the indices of the `a` where the condition is true.

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.nonzero(x > 3)


Using this result to index `a` is equivalent to using the mask directly:

>>> a[np.nonzero(a > 3)]
array([4, 5, 6, 7, 8, 9])
>>> a[a > 3]  # prefer this spelling
array([4, 5, 6, 7, 8, 9])

``nonzero`` can also be called as a method of the array.

>>> (a > 3).nonzero()
(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

#  

# np.argwhere()
`np.argwhere(a)`

**Docstring**

Find the indices of array elements that are non-zero, grouped by element.

Parameters
----------
a : array_like
    Input data.

Returns
-------
index_array : (N, a.ndim) ndarray
    Indices of elements that are non-zero. Indices are grouped by element.
    This array will have shape ``(N, a.ndim)`` where ``N`` is the number of
    non-zero items.

See Also
--------
where, nonzero

Notes
-----
``np.argwhere(a)`` is almost the same as ``np.transpose(np.nonzero(a))``,
but produces a result of the correct shape for a 0D array.

The output of ``argwhere`` is not suitable for indexing arrays.
For this purpose use ``nonzero(a)`` instead.

Examples
--------
>>> x = np.arange(6).reshape(2,3)
>>> x
array([[0, 1, 2],
       [3, 4, 5]])
>>> np.argwhere(x>1)
array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])
File:      d:\programmefiles\python\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\numeric.py
Type:      function

#  

#  

# np.newaxis

用于扩展数组维度，使得数组形状返回的数组中指定的位置增加一个所含元素为 1 的维度

### Example

In [3]:
x = np.arange(24).reshape(4, 6)
print(x[:, :, np.newaxis, np.newaxis, np.newaxis].shape)
print(x[:, :, np.newaxis].shape)
print(x[:, np.newaxis, :].shape)
print(x[:, np.newaxis].shape)
print(x[np.newaxis, :, :].shape)
print(x[np.newaxis, :].shape)
print(x[np.newaxis].shape)
print(x[1, np.newaxis])

(4, 6, 1, 1, 1)
(4, 6, 1)
(4, 1, 6)
(4, 1, 6)
(1, 4, 6)
(1, 4, 6)
(1, 4, 6)
[[ 6  7  8  9 10 11]]


In [44]:
labels = np.random.randint(1, 11, [16, 12])
vmap = np.random.randint(1, 11, [16, 4])
srows = [2, 4, 6, 9]
np.append(vmap[srows, :], labels[srows, np.newaxis], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

#  

#  

# np.squeeze()
`np.squeeze(a, axis=None)`

**Docstring**

压缩数组使其形状中维数为 1 的项去掉，即`a`的去掉长度为 1 的所有维数或一个子集

**Args**

- a: array_like, Input data.

- axis : 要 squeeze 的维度，所选轴的项大于 1 会抛出ValueError

**See Also**

- expand_dims : The inverse operation, adding singleton dimensions

**Type**:      function

#  

#  

# np.savetxt()
```python
np.savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None,
)
```

**Docstring**

将数组保存到文本文件中

**Args**

- fname: 文件名或文件句柄 (file handle)；如果文件名以``.gz``结尾，文件会自动以压缩gzip格式的压缩文件保存

- X: 1D 或 2D 类数组，要保存的数据

- fmt: 可以是单一说明符，如`"%10.5f"`，或一个说明符序列，或一个多说明符字符串，如`'Iteration %d -- %10.5f'`，在这种情况下将忽略`delimiter`参数，对于复数类型的`X`，`fmt`可以是：
    - 单一说明符`fmt='%.4e'`，生成格式化为`' (%s+%sj)' % (fmt, fmt)`的数字

    - 指定每个实部和虚部的完整字符串，例如`' %.4e %+.4ej %.4e %+.4ej %.4e %+.4ej'`表示 3 列（个）复数
    
    - 一个说明符列表，对应每列一个说明符，这种情况下实部和虚部必须有单独的说明符，例如`['%.3e + %.3ej', '(%.15e%+.15ej)']`为 2 列的说明符

- delimiter: 分隔列的字符串或字符，默认`' '`

- newline: 分隔行的字符串或字符，默认`'\n'`

- header: 将写在文件开头的字符串，默认`''`

- footer : 将写在文件末尾的字符串，默认`''`

- comments: 将被加在``header``和`footer`字符串前的字符串，以将这两者标记为注释，默认`'# '`，as expected by e.g. ``numpy.loadtxt``

- encoding: None或字符串类型，用于对输出文件进行编码的编码方式，但不适用于输出流 (ouutput streams)，如果编码不是`'bytes'`或`'latin1'`，低于 1.14 的 NumPy 版本将无法加载该文件，默认`'latin1'`


**See Also**

- save : Save an array to a binary file in NumPy ``.npy`` format
- savez : Save several arrays into an uncompressed ``.npz`` archive

关于`fmt`格式进一步说明：`fmt`的一般格式为``%flag]width[.precision]specifier``，其中
- flags:
    - ``-``: 左对齐
    - ``+``: 强制在结果前加+或-
    - ``0``: 在左边填充数字 0，见`width`
- width: 要打印的最小字符数；如果这个数值有更多字符，则不会截断这个数值
- precision:
    - 对于整数说明符例如``d,i,o,x``，就是位数的最小值
    - 对于``e, E``和``f``说明符，应为小数点后要打印的数字数
    - 对于``g``和``G``，指最大有效位数
    - 对于``s``，指最大字符数
- specifiers:
    - ``c``: 字符
    - ``d``或``i``: 带符号的十进制整数
    - ``e``或``E``: 有``e``或``E``的科学计数
    - ``f``: 十进制浮点数
    - ``g,G``: ``e,E``或``f``缩略形式
    - ``o``: 带符号的八进制数
    - ``s``: 字符组成的字符串
    - ``u``: 无符号十进制整数
    - ``x,X``: 无符号十六进制整数
关于`fmt`说明尚不完整，更多内容详见[Format Specification Mini-Language](https://docs.python.org/library/string.html#format-specification-mini-language)；




**File**: \tensorflow\lib\site-packages\numpy\lib\npyio.py

**Type**:      function

#  

# np.mgrid[]
`np.mgrid[start1:stop1:step1, start2:stop2:step2, ...]`

**Docstring**:

`np.mgrid`为`nd_grid`实例化对象，可以理解为一个 Numpy 内置的密集的多维网格，当被索引时返回所需要的网格数组，且返回数组的维度和个数与索引的维度相同；若步长不为复数，则生成的网格中终止值不包括在内；如果步长是一个复数，那么其大小的整数部分被解释为在开始值和终止值之间创建的点的数量，此时终止值包括在内

**See Also**

- numpy.lib.index_tricks.nd_grid : class of `ogrid` and `mgrid` objects
- ogrid : like mgrid but returns open (not fleshed out) mesh grids
- r_ : array concatenator

**Type**:        MGridClass

**File**:        \numpy\lib\index_tricks.py

### Examples

In [24]:
x, y = np.mgrid[1:3:1, 2:5:0.5]
print(x)
print(y)
grid = np.c_[x.ravel(), y.ravel()]
print(grid)

[[1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]]
[[2.  2.5 3.  3.5 4.  4.5]
 [2.  2.5 3.  3.5 4.  4.5]]
[[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [1.  4. ]
 [1.  4.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]
 [2.  4. ]
 [2.  4.5]]


In [18]:
x = np.mgrid[-1:1:2.5j]
print(x)

[-1.          0.33333333]


#  

2
